name: Link Checker

on:
  push:
    branches: ['main']
  pull_request:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Lychee link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress './**/*.html' './**/*.md'
          fail: true
